export const MenuItems = [
  { title: "Lịch Chiếu", url: "/#lichChieu" },
  { title: "Cụm Rạp", url: "/#cumRap" },
  { title: "Tin Tức", url: "/#tinTuc" },
  { title: "Ứng Dụng", url: "/#ungDung" },
];

export const LoginItems = [
  { title: "Đăng Nhập", url: "/login", className: "nav-links-login" },
];

export const Location = [
  "Hồ Chí Minh",
  "Hà Nội",
  "Đà Nẵng",
  "Hải Phòng",
  "Biên Hòa",
  "Nha Trang",
  "Bình Dương",
  "Phan Thiết",
  "Hạ Long",
  "Cần Thơ",
  "Vũng Tàu",
  "Quy Nhơn",
  "Huế",
  "Long Xuyên",
  "Thái Nguyên",
  "Buôn Ma Thuột",
  "Bắc Giang",
  "Bến Tre",
  "Việt Trì",
  "Ninh Bình",
  "Thái Bình",
  "Vinh",
  "Bảo Lộc",
  "Đà Lạt",
  "Trà Vinh",
  "Yên Bái",
  "Kiên Giang",
  "Vĩnh Long",
  "Cà Mau",
  "Hậu Giang",
  "Tây Ninh",
  "Tuyên Quang",
  "Thanh Hóa",
  "Nam Định",
  "Hải Dương",
  "Gia Lai",
  "Hà Tĩnh",
  "Phú Yên",
  "Bạc Liêu",
  "Long An",
  "Đồng Hới",
  "Hà Nam",
  "Bắc Ninh",
  "Quảng Trị",
  "Kon Tum",
  "Sóc Trăng",
  "Sơn La",
  "Lạng Sơn",
  "Quảng Ngãi",
  "Mỹ Tho",
  "Đồng Tháp",
  "Hưng Yên",
];
