export const UserCmtDetail = [
  {
    Cmt: "hdhd",
    Avatar: "/images/user1.jpg",
    Name: "Võ Khắc Tính",
    TimeCmt: "4",
    Rate: 6,
    CmtFrom: "/images/1200px-Facebook_circle_pictogram.svg.png",
  },
  {
    Cmt: "Dù đã đọc nhiều bình luận, nhận xét không hay về bộ phim nhưng vẫn quyết định đi coi vì ủng hộ chị đẹp Hương Giang. Phim mang tính hài hước, giải trí cao nhờ sự duyên dáng của Phát La và Puka. Về phần diễn xuất củq chị Giang thì mình thấy chưa thật sự tốt nhưng ổn cho lần đầu đóng phim. Nội dung phim như đã xem các lời giới thiệu về phim trước đó, phim sẽ tập trung vào cuộc sống của những người sau khi chuyển giới thì mình cảm thấy khá thiếu vì nội dung chưa được đào sâu để giúp mọi người hiểu được, đồng cảm, không phân biệt đối với người chuyển giới.",
    Avatar: "/images/user-cmt.jpg",
    Name: "Hachivas Le",
    TimeCmt: "10",
    Rate: 7,
    CmtFrom: "",
  },
  {
    Cmt: "Phim xem được nha mọi người. Nói về cuộc đời thế giới thứ ba",
    Avatar: "/images/user-3.jpg",
    Name: "Anh Lâm⭐⭐",
    TimeCmt: "10",
    Rate: 8,
    CmtFrom: "/images/icon-zalo.png",
  },
  {
    Cmt: "Mình thấy phim cũng khá đấy chứ! Chị Hương Giang công nhận đẹp và sức hút thật. Cốt truyện đời thường, đơn giản, được cái thích mấy miếng hài trong phim. Xem giải trí cũng ổn. 😄😄😄",
    Avatar: "/images/user-4.jpg",
    Name: "Sumika Ichigo",
    TimeCmt: "10",
    Rate: 8,
    CmtFrom: "/images/icon-zalo.png",
  },
  {
    Cmt: "Phim coi tạm được.",
    Avatar: "/images/user-5.jpg",
    Name: "Bình",
    TimeCmt: "10",
    Rate: 7,
    CmtFrom: "/images/icon-zalo.png",
  },
  {
    Cmt: "phim này xem chỉ phí tiền, khuyên các bạn đừng xem. quá dở lại còn kết thúc mở",
    Avatar: "/images/user-6.jpg",
    Name: "Lee Homi",
    TimeCmt: "10",
    Rate: 1,
    CmtFrom: "/images/1200px-Facebook_circle_pictogram.svg.png",
  },
  {
    Cmt: "Phim ở mức tạm, không cao trào, ko gây cấn, không có điểm nhấn, diễn xuất của từng nhân vật chưa toát lên được đúng bản chất ngoại trừ vai “Hân”.",
    Avatar: "/images/user-7.jpg",
    Name: "Loan Huynh",
    TimeCmt: "10",
    Rate: 6,
    CmtFrom: "",
  },
  {
    Cmt: "Phim dở nhất mình từng xem. Cốt chuyện nhạt như nước ốc và quá dễ dàng. Vì vậy ko cảm nhận và thương cảm cho nhân vật Dương. Từ phẫu thuật chuyển giới đến thi Hoa Hậu, xoẹt xoẹt là thành công, chả thấy khó khăn gì. chán",
    Avatar: "/images/user-8.jpg",
    Name: "Vi Hạ Lam",
    TimeCmt: "10",
    Rate: 1,
    CmtFrom: "/images/icon-zalo.png",
  },
  {
    Cmt: "giải trí tốt. phim đơn giản và chưa làm rõ tính cách nhân vật Dương khi còn là nam. coi cho vui thôi chứ đừng chờ đợi gì. khúc cuối khá xúc động. chắc chắn sẽ ra phần 2",
    Avatar: "/images/user-9.jpg",
    Name: "Maximilian Phước Phan",
    TimeCmt: "10",
    Rate: 6,
    CmtFrom: "/images/icon-zalo.png",
  },

  {
    Cmt: "Điểm danh team thích coi nhất khúc cuối, khúc con Hân bị đánh dập mặt đâu, tau còn muốn đánh thêm nữa kìa",
    Avatar: "/images/user-10.jpg",
    Name: "Minh Chí Nguyễn",
    TimeCmt: "10",
    Rate: 6,
    CmtFrom: "",
  },

  {
    Cmt: "Tình yêu ko có lỗi, lỗi vì chị tauuu chuyển giới quá đẹp, quá xuất sắc",
    Avatar: "/images/user-11.jpg",
    Name: "Đào Trần",
    TimeCmt: "10",
    Rate: 8,
    CmtFrom: "",
  },

  {
    Cmt: "Con Hân khúc gần cuối bị đánh lên bờ xuống ruộng, đánh tơi tả hoa lá, đánh tan bành luôn, hả dạ quá mấy mem ơii",
    Avatar: "/images/user-12.jpg",
    Name: "nhơ vết",
    TimeCmt: "10",
    Rate: 8,
    CmtFrom: "",
  },
  {
    Cmt: "Đề nghị đạo diễn phim cho Phát La vào danh mục quý hiếm cần bảo tồn vì giờ tìm bạn tốt như La tìm hổng có ra, ha ha ha",
    Avatar: "/images/user-13.jpg",
    Name: "Đào Mười",
    TimeCmt: "10",
    Rate: 8,
    CmtFrom: "",
  },
  {
    Cmt: "Phim này nhất chế Giang rồi, có quân sư lầy Phát La thì trăm trận trăm thắng, nào là lên kế hoạch đi t chuyển giới, kế hoạch cua trai này nọ chai lọ luôn ak chớ",
    Avatar: "/images/user-14.jpg",
    Name: "Tran Forget-me-not",
    TimeCmt: "10",
    Rate: 8,
    CmtFrom: "",
  },
  {
    Cmt: "500 anh em coi phim có thấy anh Tuấn đẹp trai một cách lạ lùng ko ta? chứ tui là tui thấy đẹp nhức mắt rồi đó",
    Avatar: "/images/user-15.jpg",
    Name: "Xuyến Xuyến",
    TimeCmt: "10",
    Rate: 8,
    CmtFrom: "",
  },
];
