export const API_REQUEST = "API_REQUEST";
export const API_FAILED = "API_FAILED";

export const GET_LIST_MOVIE = "GET_LIST_MOVIE";
export const GET_LIST_MOVIE_COMING = "GET_LIST_MOVIE_COMING";
export const GET_DETAIL_MOVIE = "GET_DETAIL_MOVIE";
export const GET_LIST_CINEMA_BRAND = "GET_LIST_CINEMA_BRAND";
export const GET_LIST_CINEMA_BY_BRAND = "GET_LIST_CINEMA_BY_BRAND";
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
